import type { Metadata } from "next";

import "./globals.css";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

import { Sora, Inter } from "next/font/google";
import { Toaster } from "sonner";

const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "CrisGui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${sora.className} ${inter.className}`}
      >
        <Header />
        {children}
        <Footer />
        <Toaster
          position="top-right"
          closeButton
          richColors
        />
      </body>
    </html>
  );
}
